pipeline {
    agent any
	tools
	{
		maven 'LocalMaven'
	}
    stages{
        stage('Build'){
            steps 
			{
				cmd_exec('mvn clean package')
            }
            post {
                success 
				{
                    echo 'Start saving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
    }
	
	def cmd_exec(command) 
	{
		return bat(returnStdout: true, script: "${command}").trim()
	}
}