pipeline {
    agent any
	tools
	{
		maven 'LocalMaven'
	}
	parameters
	{
		string(name: 'tomcat_dev', defaultValue: '127.0.0.1:8090', description: 'Staging Server')
		string(name: 'tomcat_prod', defaultValue: '127.0.0.1:8091', description: 'Production Server')
	}
	triggers
	{
		pollSCM('* * * * *')
	}
    stages
	{
        stage('Build')
		{
            steps 
			{
				sh 'mvn clean package'
            }
            post 
			{
                success 
				{
                    echo 'Start saving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
		stage('Deployments')
		{
			parallel
			{
				stage('Deploy to staging')
				{
					steps 
					{
						// sh "scp -i /Users/gaoyan/Documents/SunnyDemo/dev/tomcat-demo.pem.txt **/target/*.war ec2-user@${params.tomcat_dev}:/var/lib/tomcat8/webapps"
					}
				}
				stage('Deploy to production')
				{
					steps 
					{
						// sh "scp -i /Users/gaoyan/Documents/SunnyDemo/dev/tomcat-demo.pem.txt **/target/*.war ec2-user@${params.tomcat_prod}:/var/lib/tomcat8/webapps"
					}
				}
			}
		}
    }
}
	
def cmd_exec(command) 
{
	if (isUnix()) 
	{ 
		sh "${command}" 
	} 
	else 
	{ 
		bat "chcp 65001\n${command}"
	}
}