pipeline {
    agent any
	tools
	{
		maven 'LocalMaven'
	}
    stages{
        stage('Build'){
            steps 
			{
                sh '%MAVEN_HOME%\bin\mvn clean package'
            }
            post {
                success 
				{
                    echo 'Start saving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
    }
}